version: '3.3'

services:
        wordpress:
                image: wordpress:latest
                ports:
                        - "3389:80"
                restart: always
                environment:
                        WORDPRESS_DB_HOST: 10.0.0.10:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_NAME: wordpress
